In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [40]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

In [41]:
X_train[:5]

array([[ 1.82626474e+00,  5.28421998e-01,  1.86654627e+00,
         1.80749345e+00,  1.44540071e+00,  1.58213913e+00,
         2.10517073e+00,  2.65957999e+00,  2.74413443e+00,
         5.12083232e-01,  6.23955667e-01, -3.53074342e-01,
         5.88647008e-01,  6.35569990e-01, -5.51227629e-01,
        -6.43679872e-02, -2.85784923e-03,  3.29244256e-01,
         8.56257915e-01, -1.77391350e-01,  1.92564678e+00,
         9.93097842e-01,  1.95274842e+00,  1.92639279e+00,
         1.14989185e+00,  1.21105874e+00,  1.22275913e+00,
         2.37580967e+00,  4.25089550e+00,  9.75566268e-01],
       [-1.09057456e-01,  9.23325598e-01, -1.63700968e-01,
        -2.02390030e-01, -2.70072103e-01, -6.91328645e-01,
        -7.32041001e-01, -6.14996254e-01, -5.33323646e-01,
        -7.12478459e-01, -1.89596146e-01,  2.07481399e-01,
        -3.73169929e-01, -1.75006062e-01, -4.12122816e-01,
        -2.45654836e-01, -3.72934669e-01, -4.17482972e-01,
         3.92188244e-02, -4.54144150e-01, -1.62847415e-01,
         5.50453961e-01, -2.62362540e-01, -2.41378814e-01,
        -4.66202915e-01, -6.35608077e-01, -7.81765819e-01,
        -6.34834051e-01, -4.20417458e-01, -8.09029043e-01],
       [ 3.94932687e-01,  8.15415919e-01,  3.78559709e-01,
         2.48582676e-01, -3.02228481e-01, -6.99645095e-03,
         2.99695134e-01,  6.95146203e-01, -3.41384143e-01,
        -2.95366526e-01, -3.09705704e-01, -6.78483248e-01,
        -3.68721634e-01, -2.13584512e-01,  1.04575408e+00,
        -5.72694093e-02,  4.21669960e-01,  9.65237617e-01,
         4.99928087e-01, -6.14312112e-01,  6.38434067e-02,
         3.11064143e-02,  3.65207642e-02, -5.99835962e-02,
        -2.89979815e-01, -3.37658465e-01,  5.69143333e-02,
         5.25907099e-01, -5.58185935e-01, -8.76894712e-01],
       [-6.59126699e-01, -4.63428915e-01, -6.85121477e-01,
        -6.47252798e-01,  9.90272015e-02, -8.06110024e-01,
        -6.27566099e-01, -4.08076912e-01, -1.06930578e+00,
        -2.98184872e-01, -5.55730760e-01, -8.14234436e-01,
        -5.33307970e-01, -4.61772531e-01, -3.54864448e-02,
        -9.16525364e-01, -3.86547416e-01,  3.22321281e-02,
        -1.88736290e-01, -7.85375893e-01, -6.54010892e-01,
        -6.80000186e-01, -6.58864975e-01, -6.15113974e-01,
        -6.30360097e-03, -9.31695461e-01, -5.61478138e-01,
        -5.09442091e-02, -5.32554626e-01, -7.30847776e-01],
       [-9.61520791e-01, -9.31802928e-01, -9.84802842e-01,
        -8.52954507e-01, -5.87441564e-01, -1.15443194e+00,
        -1.10414660e+00, -1.25005138e+00,  4.22752500e-01,
        -4.67284292e-01, -2.44389325e-01,  1.26232910e+00,
        -3.29181373e-01, -3.73470753e-01,  6.21175587e-01,
        -8.36475194e-01, -1.01273382e+00, -1.88059044e+00,
         1.45254052e+00, -1.02835178e+00, -9.62562263e-01,
        -1.02996051e+00, -9.96916473e-01, -8.18219244e-01,
        -1.06794035e+00, -1.15571630e+00, -1.27134597e+00,
        -1.73253477e+00, -3.11484247e-01, -1.23739707e+00]], dtype=float32)

In [42]:
y_train

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.])

### Label Encoding

In [43]:
y_train = LabelEncoder().fit_transform(y_train).astype(np.float32)
y_test = LabelEncoder().fit_transform(y_test).astype(np.float32)

In [44]:
y_train

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.], dtype=float32)

### Numpy arrays to PyTorch tensors

In [45]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [46]:
type(y_train_tensor)

torch.Tensor

In [47]:
y_train_tensor.shape

torch.Size([455])

In [48]:
X_test_tensor.shape

torch.Size([114, 30])

In [49]:
X_train_tensor.dtype

torch.float32

In [50]:
X_test_tensor.dtype

torch.float32

In [51]:
y_test_tensor.dtype

torch.float32

### Defining the Model

In [66]:
import torch.nn as nn

class BreastCancerNN(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

### Important Parameeter

In [67]:
learning_rate = 0.1
epochs = 500

In [68]:
loss_function = nn.BCELoss()

In [69]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training Pipeline

In [70]:
import torch.optim as optim

In [71]:
# create model
model = BreastCancerNN(X_train_tensor.shape[1])
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

#define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # backward pass
    loss.backward()

    # parameter update
    optimizer.step()

    optimizer.zero_grad()

    # print loss in each epoch
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/500, Loss: 0.9906812310218811
Epoch 2/500, Loss: 0.6757814288139343
Epoch 3/500, Loss: 0.5066936016082764
Epoch 4/500, Loss: 0.41761988401412964
Epoch 5/500, Loss: 0.36451664566993713
Epoch 6/500, Loss: 0.3288916051387787
Epoch 7/500, Loss: 0.3029826879501343
Epoch 8/500, Loss: 0.2830488681793213
Epoch 9/500, Loss: 0.2670827805995941
Epoch 10/500, Loss: 0.25391021370887756
Epoch 11/500, Loss: 0.24279433488845825
Epoch 12/500, Loss: 0.23324614763259888
Epoch 13/500, Loss: 0.2249264419078827
Epoch 14/500, Loss: 0.2175912857055664
Epoch 15/500, Loss: 0.21106000244617462
Epoch 16/500, Loss: 0.20519542694091797
Epoch 17/500, Loss: 0.1998913735151291
Epoch 18/500, Loss: 0.19506393373012543
Epoch 19/500, Loss: 0.19064588844776154
Epoch 20/500, Loss: 0.1865827441215515
Epoch 21/500, Loss: 0.1828295737504959
Epoch 22/500, Loss: 0.17934909462928772
Epoch 23/500, Loss: 0.17611001431941986
Epoch 24/500, Loss: 0.17308591306209564
Epoch 25/500, Loss: 0.170254185795784
Epoch 26/500, Loss: 0.16759543120861053
Epoch 27/500, Loss: 0.16509287059307098
Epoch 28/500, Loss: 0.16273200511932373
Epoch 29/500, Loss: 0.16050000488758087
Epoch 30/500, Loss: 0.1583857238292694
Epoch 31/500, Loss: 0.15637926757335663
Epoch 32/500, Loss: 0.15447187423706055
Epoch 33/500, Loss: 0.1526557207107544
Epoch 34/500, Loss: 0.15092384815216064
Epoch 35/500, Loss: 0.14927001297473907
Epoch 36/500, Loss: 0.14768856763839722
Epoch 37/500, Loss: 0.14617447555065155
Epoch 38/500, Loss: 0.1447230577468872
Epoch 39/500, Loss: 0.14333026111125946
Epoch 40/500, Loss: 0.1419922262430191
Epoch 41/500, Loss: 0.14070546627044678
Epoch 42/500, Loss: 0.13946688175201416
Epoch 43/500, Loss: 0.13827352225780487
Epoch 44/500, Loss: 0.1371227651834488
Epoch 45/500, Loss: 0.13601213693618774
Epoch 46/500, Loss: 0.13493938744068146
Epoch 47/500, Loss: 0.1339024305343628
Epoch 48/500, Loss: 0.13289934396743774
Epoch 49/500, Loss: 0.13192830979824066
Epoch 50/500, Loss: 0.13098770380020142
Epoch 51/500, Loss: 0.13007599115371704
Epoch 52/500, Loss: 0.12919169664382935
Epoch 53/500, Loss: 0.12833352386951447
Epoch 54/500, Loss: 0.12750017642974854
Epoch 55/500, Loss: 0.12669053673744202
Epoch 56/500, Loss: 0.12590350210666656
Epoch 57/500, Loss: 0.12513801455497742
Epoch 58/500, Loss: 0.12439315021038055
Epoch 59/500, Loss: 0.12366798520088196
Epoch 60/500, Loss: 0.12296167016029358
Epoch 61/500, Loss: 0.12227343767881393
Epoch 62/500, Loss: 0.12160250544548035
Epoch 63/500, Loss: 0.1209481880068779
Epoch 64/500, Loss: 0.12030978500843048
Epoch 65/500, Loss: 0.11968668550252914
Epoch 66/500, Loss: 0.11907829344272614
Epoch 67/500, Loss: 0.1184840276837349
Epoch 68/500, Loss: 0.11790336668491364
Epoch 69/500, Loss: 0.11733580380678177
Epoch 70/500, Loss: 0.1167808473110199
Epoch 71/500, Loss: 0.11623803526163101
Epoch 72/500, Loss: 0.11570695787668228
Epoch 73/500, Loss: 0.11518716812133789
Epoch 74/500, Loss: 0.11467830836772919
Epoch 75/500, Loss: 0.11417997628450394
Epoch 76/500, Loss: 0.11369181424379349
Epoch 77/500, Loss: 0.11321350932121277
Epoch 78/500, Loss: 0.11274469643831253
Epoch 79/500, Loss: 0.11228509992361069
Epoch 80/500, Loss: 0.11183441430330276
Epoch 81/500, Loss: 0.11139234900474548
Epoch 82/500, Loss: 0.11095863580703735
Epoch 83/500, Loss: 0.11053303629159927
Epoch 84/500, Loss: 0.11011525243520737
Epoch 85/500, Loss: 0.1097051128745079
Epoch 86/500, Loss: 0.1093023419380188
Epoch 87/500, Loss: 0.10890673100948334
Epoch 88/500, Loss: 0.1085180938243866
Epoch 89/500, Loss: 0.10813618451356888
Epoch 90/500, Loss: 0.10776085406541824
Epoch 91/500, Loss: 0.10739190131425858
Epoch 92/500, Loss: 0.10702913999557495
Epoch 93/500, Loss: 0.10667240619659424
Epoch 94/500, Loss: 0.1063215434551239
Epoch 95/500, Loss: 0.10597638040781021
Epoch 96/500, Loss: 0.10563676804304123
Epoch 97/500, Loss: 0.10530256479978561
Epoch 98/500, Loss: 0.10497362166643143
Epoch 99/500, Loss: 0.10464980453252792
Epoch 100/500, Loss: 0.10433097928762436
Epoch 101/500, Loss: 0.10401703417301178
Epoch 102/500, Loss: 0.10370783507823944
Epoch 103/500, Loss: 0.1034032478928566
Epoch 104/500, Loss: 0.10310319066047668
Epoch 105/500, Loss: 0.10280753672122955
Epoch 106/500, Loss: 0.10251616686582565
Epoch 107/500, Loss: 0.10222899913787842
Epoch 108/500, Loss: 0.10194592922925949
Epoch 109/500, Loss: 0.10166685283184052
Epoch 110/500, Loss: 0.10139168798923492
Epoch 111/500, Loss: 0.10112032294273376
Epoch 112/500, Loss: 0.10085270553827286
Epoch 113/500, Loss: 0.10058870911598206
Epoch 114/500, Loss: 0.10032828897237778
Epoch 115/500, Loss: 0.10007134824991226
Epoch 116/500, Loss: 0.09981779754161835
Epoch 117/500, Loss: 0.09956760704517365
Epoch 118/500, Loss: 0.0993206575512886
Epoch 119/500, Loss: 0.09907689690589905
Epoch 120/500, Loss: 0.0988362580537796
Epoch 121/500, Loss: 0.0985986739397049
Epoch 122/500, Loss: 0.09836408495903015
Epoch 123/500, Loss: 0.0981324091553688
Epoch 124/500, Loss: 0.09790360927581787
Epoch 125/500, Loss: 0.09767761081457138
Epoch 126/500, Loss: 0.09745438396930695
Epoch 127/500, Loss: 0.0972338318824768
Epoch 128/500, Loss: 0.09701592475175858
Epoch 129/500, Loss: 0.09680061787366867
Epoch 130/500, Loss: 0.09658785164356232
Epoch 131/500, Loss: 0.09637755155563354
Epoch 132/500, Loss: 0.09616972506046295
Epoch 133/500, Loss: 0.09596427530050278
Epoch 134/500, Loss: 0.09576117247343063
Epoch 135/500, Loss: 0.09556037187576294
Epoch 136/500, Loss: 0.09536182880401611
Epoch 137/500, Loss: 0.09516552835702896
Epoch 138/500, Loss: 0.09497138112783432
Epoch 139/500, Loss: 0.09477937966585159
Epoch 140/500, Loss: 0.0945894718170166
Epoch 141/500, Loss: 0.09440164268016815
Epoch 142/500, Loss: 0.09421581029891968
Epoch 143/500, Loss: 0.09403198212385178
Epoch 144/500, Loss: 0.09385010600090027
Epoch 145/500, Loss: 0.09367013722658157
Epoch 146/500, Loss: 0.0934920608997345
Epoch 147/500, Loss: 0.09331583231687546
Epoch 148/500, Loss: 0.09314141422510147
Epoch 149/500, Loss: 0.09296879917383194
Epoch 150/500, Loss: 0.09279793500900269
Epoch 151/500, Loss: 0.09262879937887192
Epoch 152/500, Loss: 0.09246135503053665
Epoch 153/500, Loss: 0.09229560196399689
Epoch 154/500, Loss: 0.09213147312402725
Epoch 155/500, Loss: 0.09196896106004715
Epoch 156/500, Loss: 0.09180803596973419
Epoch 157/500, Loss: 0.09164868295192719
Epoch 158/500, Loss: 0.09149087965488434
Epoch 159/500, Loss: 0.09133455902338028
Epoch 160/500, Loss: 0.0911797508597374
Epoch 161/500, Loss: 0.09102639555931091
Epoch 162/500, Loss: 0.09087449312210083
Epoch 163/500, Loss: 0.09072400629520416
Epoch 164/500, Loss: 0.09057491272687912
Epoch 165/500, Loss: 0.0904272049665451
Epoch 166/500, Loss: 0.09028084576129913
Epoch 167/500, Loss: 0.09013581275939941
Epoch 168/500, Loss: 0.08999210596084595
Epoch 169/500, Loss: 0.08984969556331635
Epoch 170/500, Loss: 0.08970855176448822
Epoch 171/500, Loss: 0.08956867456436157
Epoch 172/500, Loss: 0.08943002671003342
Epoch 173/500, Loss: 0.08929260075092316
Epoch 174/500, Loss: 0.08915635943412781
Epoch 175/500, Loss: 0.08902131766080856
Epoch 176/500, Loss: 0.08888744562864304
Epoch 177/500, Loss: 0.08875472843647003
Epoch 178/500, Loss: 0.08862312883138657
Epoch 179/500, Loss: 0.08849265426397324
Epoch 180/500, Loss: 0.08836326748132706
Epoch 181/500, Loss: 0.08823496848344803
Epoch 182/500, Loss: 0.08810777217149734
Epoch 183/500, Loss: 0.08798160403966904
Epoch 184/500, Loss: 0.0878564789891243
Epoch 185/500, Loss: 0.08773237466812134
Epoch 186/500, Loss: 0.08760929107666016
Epoch 187/500, Loss: 0.08748720586299896
Epoch 188/500, Loss: 0.08736611157655716
Epoch 189/500, Loss: 0.08724598586559296
Epoch 190/500, Loss: 0.08712681382894516
Epoch 191/500, Loss: 0.08700858056545258
Epoch 192/500, Loss: 0.0868912935256958
Epoch 193/500, Loss: 0.08677493035793304
Epoch 194/500, Loss: 0.08665947616100311
Epoch 195/500, Loss: 0.08654491603374481
Epoch 196/500, Loss: 0.08643122762441635
Epoch 197/500, Loss: 0.08631843328475952
Epoch 198/500, Loss: 0.08620648831129074
Epoch 199/500, Loss: 0.0860954150557518
Epoch 200/500, Loss: 0.08598516136407852
Epoch 201/500, Loss: 0.0858757495880127
Epoch 202/500, Loss: 0.08576715737581253
Epoch 203/500, Loss: 0.08565936237573624
Epoch 204/500, Loss: 0.08555237203836441
Epoch 205/500, Loss: 0.08544618636369705
Epoch 206/500, Loss: 0.08534076064825058
Epoch 207/500, Loss: 0.08523612469434738
Epoch 208/500, Loss: 0.08513224124908447
Epoch 209/500, Loss: 0.08502909541130066
Epoch 210/500, Loss: 0.08492670953273773
Epoch 211/500, Loss: 0.0848250538110733
Epoch 212/500, Loss: 0.08472410589456558
Epoch 213/500, Loss: 0.08462390303611755
Epoch 214/500, Loss: 0.08452439308166504
Epoch 215/500, Loss: 0.08442558348178864
Epoch 216/500, Loss: 0.08432745933532715
Epoch 217/500, Loss: 0.08423001319169998
Epoch 218/500, Loss: 0.08413325995206833
Epoch 219/500, Loss: 0.0840371623635292
Epoch 220/500, Loss: 0.08394172787666321
Epoch 221/500, Loss: 0.08384693413972855
Epoch 222/500, Loss: 0.08375279605388641
Epoch 223/500, Loss: 0.08365930616855621
Epoch 224/500, Loss: 0.08356642723083496
Epoch 225/500, Loss: 0.08347418159246445
Epoch 226/500, Loss: 0.08338253945112228
Epoch 227/500, Loss: 0.08329151570796967
Epoch 228/500, Loss: 0.0832010954618454
Epoch 229/500, Loss: 0.08311126381158829
Epoch 230/500, Loss: 0.08302201330661774
Epoch 231/500, Loss: 0.08293336629867554
Epoch 232/500, Loss: 0.0828452780842781
Epoch 233/500, Loss: 0.08275777101516724
Epoch 234/500, Loss: 0.08267080783843994
Epoch 235/500, Loss: 0.0825844258069992
Epoch 236/500, Loss: 0.08249858021736145
Epoch 237/500, Loss: 0.08241329342126846
Epoch 238/500, Loss: 0.08232852816581726
Epoch 239/500, Loss: 0.08224429935216904
Epoch 240/500, Loss: 0.08216061443090439
Epoch 241/500, Loss: 0.08207743614912033
Epoch 242/500, Loss: 0.08199477940797806
Epoch 243/500, Loss: 0.08191263675689697
Epoch 244/500, Loss: 0.08183100819587708
Epoch 245/500, Loss: 0.08174987882375717
Epoch 246/500, Loss: 0.08166923373937607
Epoch 247/500, Loss: 0.08158908039331436
Epoch 248/500, Loss: 0.08150941878557205
Epoch 249/500, Loss: 0.08143024146556854
Epoch 250/500, Loss: 0.08135152608156204
Epoch 251/500, Loss: 0.08127328753471375
Epoch 252/500, Loss: 0.08119554072618484
Epoch 253/500, Loss: 0.08111821860074997
Epoch 254/500, Loss: 0.0810413658618927
Epoch 255/500, Loss: 0.08096496760845184
Epoch 256/500, Loss: 0.0808890238404274
Epoch 257/500, Loss: 0.08081351220607758
Epoch 258/500, Loss: 0.08073845505714417
Epoch 259/500, Loss: 0.08066383004188538
Epoch 260/500, Loss: 0.08058962225914001
Epoch 261/500, Loss: 0.08051585406064987
Epoch 262/500, Loss: 0.08044248819351196
Epoch 263/500, Loss: 0.08036956936120987
Epoch 264/500, Loss: 0.08029704540967941
Epoch 265/500, Loss: 0.08022493869066238
Epoch 266/500, Loss: 0.08015323430299759
Epoch 267/500, Loss: 0.08008193969726562
Epoch 268/500, Loss: 0.0800110399723053
Epoch 269/500, Loss: 0.07994052767753601
Epoch 270/500, Loss: 0.07987041771411896
Epoch 271/500, Loss: 0.07980069518089294
Epoch 272/500, Loss: 0.07973136007785797
Epoch 273/500, Loss: 0.07966239750385284
Epoch 274/500, Loss: 0.07959380000829697
Epoch 275/500, Loss: 0.07952559739351273
Epoch 276/500, Loss: 0.07945775240659714
Epoch 277/500, Loss: 0.0793902799487114
Epoch 278/500, Loss: 0.0793231725692749
Epoch 279/500, Loss: 0.07925642281770706
Epoch 280/500, Loss: 0.07919003814458847
Epoch 281/500, Loss: 0.07912398129701614
Epoch 282/500, Loss: 0.07905830442905426
Epoch 283/500, Loss: 0.07899295538663864
Epoch 284/500, Loss: 0.07892796397209167
Epoch 285/500, Loss: 0.07886330783367157
Epoch 286/500, Loss: 0.07879899442195892
Epoch 287/500, Loss: 0.07873500883579254
Epoch 288/500, Loss: 0.07867135852575302
Epoch 289/500, Loss: 0.07860803604125977
Epoch 290/500, Loss: 0.07854504138231277
Epoch 291/500, Loss: 0.07848237454891205
Epoch 292/500, Loss: 0.07842002809047699
Epoch 293/500, Loss: 0.0783580020070076
Epoch 294/500, Loss: 0.07829628139734268
Epoch 295/500, Loss: 0.07823487371206284
Epoch 296/500, Loss: 0.07817377895116806
Epoch 297/500, Loss: 0.07811298221349716
Epoch 298/500, Loss: 0.07805251330137253
Epoch 299/500, Loss: 0.07799233496189117
Epoch 300/500, Loss: 0.0779324546456337
Epoch 301/500, Loss: 0.0778728723526001
Epoch 302/500, Loss: 0.07781358063220978
Epoch 303/500, Loss: 0.07775457948446274
Epoch 304/500, Loss: 0.07769587635993958
Epoch 305/500, Loss: 0.0776374563574791
Epoch 306/500, Loss: 0.0775793269276619
Epoch 307/500, Loss: 0.07752147316932678
Epoch 308/500, Loss: 0.07746390998363495
Epoch 309/500, Loss: 0.0774066150188446
Epoch 310/500, Loss: 0.07734960317611694
Epoch 311/500, Loss: 0.07729285210371017
Epoch 312/500, Loss: 0.07723637670278549
Epoch 313/500, Loss: 0.0771801769733429
Epoch 314/500, Loss: 0.07712423801422119
Epoch 315/500, Loss: 0.07706857472658157
Epoch 316/500, Loss: 0.07701315730810165
Epoch 317/500, Loss: 0.07695800811052322
Epoch 318/500, Loss: 0.07690311968326569
Epoch 319/500, Loss: 0.07684849202632904
Epoch 320/500, Loss: 0.07679411768913269
Epoch 321/500, Loss: 0.07673998922109604
Epoch 322/500, Loss: 0.07668611407279968
Epoch 323/500, Loss: 0.07663247734308243
Epoch 324/500, Loss: 0.07657910138368607
Epoch 325/500, Loss: 0.0765259638428688
Epoch 326/500, Loss: 0.07647307962179184
Epoch 327/500, Loss: 0.07642042636871338
Epoch 328/500, Loss: 0.07636801153421402
Epoch 329/500, Loss: 0.07631584256887436
Epoch 330/500, Loss: 0.0762638971209526
Epoch 331/500, Loss: 0.07621220499277115
Epoch 332/500, Loss: 0.0761607214808464
Epoch 333/500, Loss: 0.07610947638750076
Epoch 334/500, Loss: 0.07605845481157303
Epoch 335/500, Loss: 0.0760076642036438
Epoch 336/500, Loss: 0.07595710456371307
Epoch 337/500, Loss: 0.07590676844120026
Epoch 338/500, Loss: 0.07585664838552475
Epoch 339/500, Loss: 0.07580675184726715
Epoch 340/500, Loss: 0.07575707137584686
Epoch 341/500, Loss: 0.07570759952068329
Epoch 342/500, Loss: 0.07565835863351822
Epoch 343/500, Loss: 0.07560931891202927
Epoch 344/500, Loss: 0.07556050270795822
Epoch 345/500, Loss: 0.0755118876695633
Epoch 346/500, Loss: 0.07546348124742508
Epoch 347/500, Loss: 0.07541529089212418
Epoch 348/500, Loss: 0.07536730170249939
Epoch 349/500, Loss: 0.07531952112913132
Epoch 350/500, Loss: 0.07527193427085876
Epoch 351/500, Loss: 0.07522454857826233
Epoch 352/500, Loss: 0.07517737150192261
Epoch 353/500, Loss: 0.0751303881406784
Epoch 354/500, Loss: 0.07508360594511032
Epoch 355/500, Loss: 0.07503702491521835
Epoch 356/500, Loss: 0.07499060779809952
Epoch 357/500, Loss: 0.07494442164897919
Epoch 358/500, Loss: 0.07489841431379318
Epoch 359/500, Loss: 0.0748525932431221
Epoch 360/500, Loss: 0.07480696588754654
Epoch 361/500, Loss: 0.0747615247964859
Epoch 362/500, Loss: 0.07471626996994019
Epoch 363/500, Loss: 0.0746711865067482
Epoch 364/500, Loss: 0.07462631165981293
Epoch 365/500, Loss: 0.07458160817623138
Epoch 366/500, Loss: 0.07453709095716476
Epoch 367/500, Loss: 0.07449275255203247
Epoch 368/500, Loss: 0.07444857805967331
Epoch 369/500, Loss: 0.07440460473299026
Epoch 370/500, Loss: 0.07436078786849976
Epoch 371/500, Loss: 0.07431715726852417
Epoch 372/500, Loss: 0.07427369803190231
Epoch 373/500, Loss: 0.07423041760921478
Epoch 374/500, Loss: 0.07418729364871979
Epoch 375/500, Loss: 0.07414434850215912
Epoch 376/500, Loss: 0.07410158216953278
Epoch 377/500, Loss: 0.07405897974967957
Epoch 378/500, Loss: 0.07401653379201889
Epoch 379/500, Loss: 0.07397427409887314
Epoch 380/500, Loss: 0.07393216341733932
Epoch 381/500, Loss: 0.07389022409915924
Epoch 382/500, Loss: 0.07384844869375229
Epoch 383/500, Loss: 0.07380682229995728
Epoch 384/500, Loss: 0.07376537472009659
Epoch 385/500, Loss: 0.07372406870126724
Epoch 386/500, Loss: 0.07368293404579163
Epoch 387/500, Loss: 0.07364195585250854
Epoch 388/500, Loss: 0.0736011266708374
Epoch 389/500, Loss: 0.07356046140193939
Epoch 390/500, Loss: 0.07351995259523392
Epoch 391/500, Loss: 0.07347958534955978
Epoch 392/500, Loss: 0.07343938946723938
Epoch 393/500, Loss: 0.07339933514595032
Epoch 394/500, Loss: 0.0733594298362732
Epoch 395/500, Loss: 0.07331967353820801
Epoch 396/500, Loss: 0.07328006625175476
Epoch 397/500, Loss: 0.07324060797691345
Epoch 398/500, Loss: 0.07320129871368408
Epoch 399/500, Loss: 0.07316213846206665
Epoch 400/500, Loss: 0.07312311977148056
Epoch 401/500, Loss: 0.07308425009250641
Epoch 402/500, Loss: 0.0730455070734024
Epoch 403/500, Loss: 0.07300692796707153
Epoch 404/500, Loss: 0.0729684829711914
Epoch 405/500, Loss: 0.07293017208576202
Epoch 406/500, Loss: 0.07289201021194458
Epoch 407/500, Loss: 0.07285397499799728
Epoch 408/500, Loss: 0.07281609624624252
Epoch 409/500, Loss: 0.07277833670377731
Epoch 410/500, Loss: 0.07274072617292404
Epoch 411/500, Loss: 0.07270324975252151
Epoch 412/500, Loss: 0.07266590744256973
Epoch 413/500, Loss: 0.0726286917924881
Epoch 414/500, Loss: 0.07259161025285721
Epoch 415/500, Loss: 0.07255467772483826
Epoch 416/500, Loss: 0.07251786440610886
Epoch 417/500, Loss: 0.0724811851978302
Epoch 418/500, Loss: 0.07244463264942169
Epoch 419/500, Loss: 0.07240821421146393
Epoch 420/500, Loss: 0.07237191498279572
Epoch 421/500, Loss: 0.07233575731515884
Epoch 422/500, Loss: 0.07229971140623093
Epoch 423/500, Loss: 0.07226379960775375
Epoch 424/500, Loss: 0.07222799956798553
Epoch 425/500, Loss: 0.07219234853982925
Epoch 426/500, Loss: 0.07215681672096252
Epoch 427/500, Loss: 0.07212139666080475
Epoch 428/500, Loss: 0.07208611071109772
Epoch 429/500, Loss: 0.07205093652009964
Epoch 430/500, Loss: 0.07201588153839111
Epoch 431/500, Loss: 0.07198095321655273
Epoch 432/500, Loss: 0.0719461441040039
Epoch 433/500, Loss: 0.07191145420074463
Epoch 434/500, Loss: 0.0718768984079361
Epoch 435/500, Loss: 0.07184243947267532
Epoch 436/500, Loss: 0.0718081071972847
Epoch 437/500, Loss: 0.07177388668060303
Epoch 438/500, Loss: 0.07173977792263031
Epoch 439/500, Loss: 0.07170579582452774
Epoch 440/500, Loss: 0.07167192548513412
Epoch 441/500, Loss: 0.07163816690444946
Epoch 442/500, Loss: 0.07160452008247375
Epoch 443/500, Loss: 0.0715709775686264
Epoch 444/500, Loss: 0.0715375617146492
Epoch 445/500, Loss: 0.07150425016880035
Epoch 446/500, Loss: 0.07147104293107986
Epoch 447/500, Loss: 0.07143796235322952
Epoch 448/500, Loss: 0.07140498608350754
Epoch 449/500, Loss: 0.07137210667133331
Epoch 450/500, Loss: 0.07133933901786804
Epoch 451/500, Loss: 0.07130668312311172
Epoch 452/500, Loss: 0.07127413898706436
Epoch 453/500, Loss: 0.07124169170856476
Epoch 454/500, Loss: 0.0712093636393547
Epoch 455/500, Loss: 0.07117713987827301
Epoch 456/500, Loss: 0.07114501297473907
Epoch 457/500, Loss: 0.0711129829287529
Epoch 458/500, Loss: 0.07108106464147568
Epoch 459/500, Loss: 0.07104925066232681
Epoch 460/500, Loss: 0.07101753354072571
Epoch 461/500, Loss: 0.07098593562841415
Epoch 462/500, Loss: 0.07095442712306976
Epoch 463/500, Loss: 0.07092302292585373
Epoch 464/500, Loss: 0.07089171558618546
Epoch 465/500, Loss: 0.07086049765348434
Epoch 466/500, Loss: 0.07082938402891159
Epoch 467/500, Loss: 0.07079838216304779
Epoch 468/500, Loss: 0.07076746970415115
Epoch 469/500, Loss: 0.07073666155338287
Epoch 470/500, Loss: 0.07070594280958176
Epoch 471/500, Loss: 0.0706753209233284
Epoch 472/500, Loss: 0.0706447958946228
Epoch 473/500, Loss: 0.07061436772346497
Epoch 474/500, Loss: 0.07058403640985489
Epoch 475/500, Loss: 0.07055380195379257
Epoch 476/500, Loss: 0.07052365690469742
Epoch 477/500, Loss: 0.07049360871315002
Epoch 478/500, Loss: 0.0704636424779892
Epoch 479/500, Loss: 0.07043378055095673
Epoch 480/500, Loss: 0.07040401548147202
Epoch 481/500, Loss: 0.07037433236837387
Epoch 482/500, Loss: 0.07034474611282349
Epoch 483/500, Loss: 0.07031524926424026
Epoch 484/500, Loss: 0.0702858418226242
Epoch 485/500, Loss: 0.07025652378797531
Epoch 486/500, Loss: 0.07022729516029358
Epoch 487/500, Loss: 0.07019814848899841
Epoch 488/500, Loss: 0.0701691210269928
Epoch 489/500, Loss: 0.07014014571905136
Epoch 490/500, Loss: 0.07011126726865768
Epoch 491/500, Loss: 0.07008247822523117
Epoch 492/500, Loss: 0.07005378603935242

In [72]:
model.linear.weight

Parameter containing:
tensor([[ 0.5355,  0.5667,  0.4263,  0.5068,  0.2494, -0.0114,  0.5513,  0.7127,
          0.0820, -0.3626,  0.5452, -0.0070,  0.4062,  0.4196,  0.0494, -0.1471,
         -0.1677, -0.0947, -0.2323, -0.3951,  0.7008,  0.6816,  0.8570,  0.8281,
          0.6474,  0.1269,  0.4650,  0.6648,  0.4696,  0.0873]],
       requires_grad=True)

### Evaluation

In [73]:
# model evaluation

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred >= 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()*100:.2f}%')

Accuracy: 51.35%