In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train[:5]

array([[-3.82333646e-01, -3.52757971e-01, -4.36108887e-01,
        -4.18509899e-01, -1.26475994e+00, -1.09853871e+00,
        -9.21293397e-01, -7.71516141e-01, -1.25902708e+00,
        -1.04611666e+00, -3.84838057e-01, -6.12970674e-01,
        -3.67200360e-01, -3.60857323e-01,  1.20835156e-01,
        -7.58543946e-01, -8.49488029e-01, -1.00173784e+00,
        -1.48701734e-01, -9.65970770e-01, -4.88861435e-01,
        -7.53672453e-01, -5.30729581e-01, -4.97873148e-01,
        -1.13674996e+00, -9.82593006e-01, -1.10380163e+00,
        -1.16870672e+00, -1.16356524e+00, -1.28202011e+00],
       [-7.92025185e-01, -8.70823690e-01, -7.46674787e-01,
        -7.25593677e-01, -9.30095548e-01,  1.07632469e-01,
         1.22804432e-01, -5.41432133e-01, -1.74146819e-02,
         1.32066228e+00, -2.64590517e-01, -2.68690284e-01,
        -1.51548769e-01, -3.66407808e-01,  1.20611213e+00,
         2.18460468e+00,  1.95348834e+00,  1.38803340e+00,
        -9.96072064e-01,  3.01830712e+00, -8.55456815e-01,
        -1.09300618e+00, -8.00106820e-01, -7.35621487e-01,
        -9.85960352e-01,  1.46917207e-01,  1.18697708e-01,
        -4.76428809e-01, -1.17617627e+00,  1.05124166e+00],
       [ 2.25140016e-01,  2.53641534e-01,  1.82571077e-01,
         8.60852190e-02, -5.81128384e-02, -4.01773462e-01,
        -2.68190209e-01,  6.07796706e-03, -1.15998108e+00,
        -7.63433458e-01, -6.01009561e-01,  7.99442442e-01,
        -6.07698764e-01, -3.89637615e-01, -5.64640474e-01,
        -6.53029791e-01, -3.42870845e-01, -2.65990612e-03,
        -1.26371586e-01, -7.40135467e-01, -3.78255458e-02,
         5.03366761e-01, -8.77602248e-02, -1.55849223e-01,
        -4.80371649e-01, -7.21372765e-01, -4.85214497e-01,
        -1.94466688e-01, -8.41983905e-01, -9.77981007e-01],
       [ 1.08407952e+00,  4.47020904e-01,  1.33820314e+00,
         9.65755216e-01,  1.87780295e+00,  2.77221734e+00,
         2.75111715e+00,  1.76015659e+00,  1.05440457e+00,
         1.13082112e+00, -1.62159686e-02, -8.17398888e-01,
         1.08170755e-01,  1.47254790e-02,  5.73519810e-02,
         6.04034779e-01,  9.15906726e-01, -2.15126938e-01,
        -5.58871283e-01,  4.34422510e-01,  9.48686741e-01,
         3.86355132e-01,  1.25912597e+00,  7.48567702e-01,
         2.43341587e+00,  2.04603419e+00,  2.86761829e+00,
         1.21237277e+00,  5.38924162e-01,  1.87225318e+00],
       [-1.08264133e-01, -7.34741911e-01, -1.55782298e-01,
        -1.99926936e-01, -9.75050466e-01, -7.61000327e-01,
        -7.82289141e-01, -7.22604573e-01,  2.01901469e-01,
        -8.72903913e-01, -8.12727452e-01, -1.32067900e+00,
        -7.12711712e-01, -5.50807246e-01, -9.87267228e-01,
        -5.37339145e-01, -6.51603928e-01, -8.87134408e-01,
        -1.45175921e-01, -6.09708433e-01, -2.78789925e-01,
        -8.79042055e-01, -2.27459143e-01, -3.52234912e-01,
        -9.72655386e-01, -2.88755383e-01, -6.47050168e-01,
        -6.67325187e-01,  6.61881730e-01, -3.94268300e-01]])

In [11]:
y_train

429    B
388    B
495    B
400    M
374    B
      ..
35     M
68     B
195    B
63     B
462    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [12]:
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0])

### Numpy arrays to PyTorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

### Defining the Model

In [41]:
class BreastCancerNN():
    def __init__(self, X):

        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameeter

In [65]:
learning_rate = 0.1
epochs = 500

## Training Pipeline

In [66]:
# create model
model = BreastCancerNN(X_train_tensor)

#define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/500, Loss: 3.887866562923082
Epoch 1/500, Loss: 3.887866562923082
Epoch 2/500, Loss: 3.7696428582748323
Epoch 2/500, Loss: 3.7696428582748323
Epoch 3/500, Loss: 3.6466382304820995
Epoch 3/500, Loss: 3.6466382304820995
Epoch 4/500, Loss: 3.5180128271808746
Epoch 4/500, Loss: 3.5180128271808746
Epoch 5/500, Loss: 3.388255795959296
Epoch 5/500, Loss: 3.388255795959296
Epoch 6/500, Loss: 3.257204434316756
Epoch 6/500, Loss: 3.257204434316756
Epoch 7/500, Loss: 3.12059609271143
Epoch 7/500, Loss: 3.12059609271143
Epoch 8/500, Loss: 2.9745086152949507
Epoch 8/500, Loss: 2.9745086152949507
Epoch 9/500, Loss: 2.825183927939035
Epoch 9/500, Loss: 2.825183927939035
Epoch 10/500, Loss: 2.674023000819219
Epoch 10/500, Loss: 2.674023000819219
Epoch 11/500, Loss: 2.5232620587608534
Epoch 11/500, Loss: 2.5232620587608534
Epoch 12/500, Loss: 2.3706659925213636
Epoch 12/500, Loss: 2.3706659925213636
Epoch 13/500, Loss: 2.212552384888073
Epoch 13/500, Loss: 2.212552384888073
Epoch 14/500, Loss: 2.0551630591304337
Epoch 14/500, Loss: 2.0551630591304337
Epoch 15/500, Loss: 1.8970117706445084
Epoch 15/500, Loss: 1.8970117706445084
Epoch 16/500, Loss: 1.741785307427974
Epoch 16/500, Loss: 1.741785307427974
Epoch 17/500, Loss: 1.5948144037025989
Epoch 17/500, Loss: 1.5948144037025989
Epoch 18/500, Loss: 1.4573562022505686
Epoch 18/500, Loss: 1.4573562022505686
Epoch 19/500, Loss: 1.3335176939500724
Epoch 19/500, Loss: 1.3335176939500724
Epoch 20/500, Loss: 1.2251981132892902
Epoch 20/500, Loss: 1.2251981132892902
Epoch 21/500, Loss: 1.133942380825517
Epoch 21/500, Loss: 1.133942380825517
Epoch 22/500, Loss: 1.0599477229769407
Epoch 22/500, Loss: 1.0599477229769407
Epoch 23/500, Loss: 1.0014293251325719
Epoch 23/500, Loss: 1.0014293251325719
Epoch 24/500, Loss: 0.9555538155319194
Epoch 24/500, Loss: 0.9555538155319194
Epoch 25/500, Loss: 0.9195285060111364
Epoch 25/500, Loss: 0.9195285060111364
Epoch 26/500, Loss: 0.8909623909026446
Epoch 26/500, Loss: 0.8909623909026446
Epoch 27/500, Loss: 0.8679408980599455
Epoch 27/500, Loss: 0.8679408980599455
Epoch 28/500, Loss: 0.8490043108769456
Epoch 28/500, Loss: 0.8490043108769456
Epoch 29/500, Loss: 0.8330792643585603
Epoch 29/500, Loss: 0.8330792643585603
Epoch 30/500, Loss: 0.8193972704863368
Epoch 30/500, Loss: 0.8193972704863368
Epoch 31/500, Loss: 0.8074181829640367
Epoch 31/500, Loss: 0.8074181829640367
Epoch 32/500, Loss: 0.7967660515774447
Epoch 32/500, Loss: 0.7967660515774447
Epoch 33/500, Loss: 0.7871793073608571
Epoch 33/500, Loss: 0.7871793073608571
Epoch 34/500, Loss: 0.7784742006535168
Epoch 34/500, Loss: 0.7784742006535168
Epoch 35/500, Loss: 0.7705190790558712
Epoch 35/500, Loss: 0.7705190790558712
Epoch 36/500, Loss: 0.7632168609386311
Epoch 36/500, Loss: 0.7632168609386311
Epoch 37/500, Loss: 0.756493380683098
Epoch 37/500, Loss: 0.756493380683098
Epoch 38/500, Loss: 0.7502897805280162
Epoch 38/500, Loss: 0.7502897805280162
Epoch 39/500, Loss: 0.7445576101451402
Epoch 39/500, Loss: 0.7445576101451402
Epoch 40/500, Loss: 0.7392556961497334
Epoch 40/500, Loss: 0.7392556961497334
Epoch 41/500, Loss: 0.7343481467094307
Epoch 41/500, Loss: 0.7343481467094307
Epoch 42/500, Loss: 0.7298030729280034
Epoch 42/500, Loss: 0.7298030729280034
Epoch 43/500, Loss: 0.7255917574613069
Epoch 43/500, Loss: 0.7255917574613069
Epoch 44/500, Loss: 0.7216880999932362
Epoch 44/500, Loss: 0.7216880999932362
Epoch 45/500, Loss: 0.7180682336512917
Epoch 45/500, Loss: 0.7180682336512917
Epoch 46/500, Loss: 0.7147102474189454
Epoch 46/500, Loss: 0.7147102474189454
Epoch 47/500, Loss: 0.7115939751510062
Epoch 47/500, Loss: 0.7115939751510062
Epoch 48/500, Loss: 0.7087008274525765
Epoch 48/500, Loss: 0.7087008274525765
Epoch 49/500, Loss: 0.706013652129477
Epoch 49/500, Loss: 0.706013652129477
Epoch 50/500, Loss: 0.7035166145489966
Epoch 50/500, Loss: 0.7035166145489966
Epoch 51/500, Loss: 0.701195092577284
Epoch 51/500, Loss: 0.701195092577284
Epoch 52/500, Loss: 0.6990355827195199
Epoch 52/500, Loss: 0.6990355827195199
Epoch 53/500, Loss: 0.6970256152481911
Epoch 53/500, Loss: 0.6970256152481911
Epoch 54/500, Loss: 0.6951536768001202
Epoch 54/500, Loss: 0.6951536768001202
Epoch 55/500, Loss: 0.6934091393508947
Epoch 55/500, Loss: 0.6934091393508947
Epoch 56/500, Loss: 0.6917821947486805
Epoch 56/500, Loss: 0.6917821947486805
Epoch 57/500, Loss: 0.6902637941720023
Epoch 57/500, Loss: 0.6902637941720023
Epoch 58/500, Loss: 0.6888455920037599
Epoch 58/500, Loss: 0.6888455920037599
Epoch 59/500, Loss: 0.6875198937067576
Epoch 59/500, Loss: 0.6875198937067576
Epoch 60/500, Loss: 0.6862796073558572
Epoch 60/500, Loss: 0.6862796073558572
Epoch 61/500, Loss: 0.6851181985353619
Epoch 61/500, Loss: 0.6851181985353619
Epoch 62/500, Loss: 0.6840296483516982
Epoch 62/500, Loss: 0.6840296483516982
Epoch 63/500, Loss: 0.6830084143437144
Epoch 63/500, Loss: 0.6830084143437144
Epoch 64/500, Loss: 0.6820493940981178
Epoch 64/500, Loss: 0.6820493940981178
Epoch 65/500, Loss: 0.6811478913972362
Epoch 65/500, Loss: 0.6811478913972362
Epoch 66/500, Loss: 0.6802995847417506
Epoch 66/500, Loss: 0.6802995847417506
Epoch 67/500, Loss: 0.6795004981032596
Epoch 67/500, Loss: 0.6795004981032596
Epoch 68/500, Loss: 0.6787469737713506
Epoch 68/500, Loss: 0.6787469737713506
Epoch 69/500, Loss: 0.6780356471678999
Epoch 69/500, Loss: 0.6780356471678999
Epoch 70/500, Loss: 0.6773634235081099
Epoch 70/500, Loss: 0.6773634235081099
Epoch 71/500, Loss: 0.6767274561937001
Epoch 71/500, Loss: 0.6767274561937001
Epoch 72/500, Loss: 0.6761251268290057
Epoch 72/500, Loss: 0.6761251268290057
Epoch 73/500, Loss: 0.6755540267556805
Epoch 73/500, Loss: 0.6755540267556805
Epoch 74/500, Loss: 0.6750119400064298
Epoch 74/500, Loss: 0.6750119400064298
Epoch 75/500, Loss: 0.674496827582779
Epoch 75/500, Loss: 0.674496827582779
Epoch 76/500, Loss: 0.6740068129663949
Epoch 76/500, Loss: 0.6740068129663949
Epoch 77/500, Loss: 0.6735401687779365
Epoch 77/500, Loss: 0.6735401687779365
Epoch 78/500, Loss: 0.6730953045018243
Epoch 78/500, Loss: 0.6730953045018243
Epoch 79/500, Loss: 0.6726707551997088
Epoch 79/500, Loss: 0.6726707551997088
Epoch 80/500, Loss: 0.6722651711397277
Epoch 80/500, Loss: 0.6722651711397277
Epoch 81/500, Loss: 0.6718773082729076
Epoch 81/500, Loss: 0.6718773082729076
Epoch 82/500, Loss: 0.6715060194922187
Epoch 82/500, Loss: 0.6715060194922187
Epoch 83/500, Loss: 0.6711502466138545
Epoch 83/500, Loss: 0.6711502466138545
Epoch 84/500, Loss: 0.6708090130242327
Epoch 84/500, Loss: 0.6708090130242327
Epoch 85/500, Loss: 0.6704814169400101
Epoch 85/500, Loss: 0.6704814169400101
Epoch 86/500, Loss: 0.6701666252320317
Epoch 86/500, Loss: 0.6701666252320317
Epoch 87/500, Loss: 0.6698638677676224
Epoch 87/500, Loss: 0.6698638677676224
Epoch 88/500, Loss: 0.669572432228921
Epoch 88/500, Loss: 0.669572432228921
Epoch 89/500, Loss: 0.6692916593681016
Epoch 89/500, Loss: 0.6692916593681016
Epoch 90/500, Loss: 0.6690209386632741
Epoch 90/500, Loss: 0.6690209386632741
Epoch 91/500, Loss: 0.6687597043416443
Epoch 91/500, Loss: 0.6687597043416443
Epoch 92/500, Loss: 0.6685074317391239
Epoch 92/500, Loss: 0.6685074317391239
Epoch 93/500, Loss: 0.6682636339680138
Epoch 93/500, Loss: 0.6682636339680138
Epoch 94/500, Loss: 0.668027858866671
Epoch 94/500, Loss: 0.668027858866671
Epoch 95/500, Loss: 0.6677996862071782
Epoch 95/500, Loss: 0.6677996862071782
Epoch 96/500, Loss: 0.6675787251390094
Epoch 96/500, Loss: 0.6675787251390094
Epoch 97/500, Loss: 0.667364611848502
Epoch 97/500, Loss: 0.667364611848502
Epoch 98/500, Loss: 0.6671570074156326
Epoch 98/500, Loss: 0.6671570074156326
Epoch 99/500, Loss: 0.6669555958511512
Epoch 99/500, Loss: 0.6669555958511512
Epoch 100/500, Loss: 0.6667600822985623
Epoch 100/500, Loss: 0.6667600822985623
Epoch 101/500, Loss: 0.6665701913867605
Epoch 101/500, Loss: 0.6665701913867605
Epoch 102/500, Loss: 0.6663856657203466
Epoch 102/500, Loss: 0.6663856657203466
Epoch 103/500, Loss: 0.6662062644957606
Epoch 103/500, Loss: 0.6662062644957606
Epoch 104/500, Loss: 0.6660317622323956
Epoch 104/500, Loss: 0.6660317622323956
Epoch 105/500, Loss: 0.665861947608793
Epoch 105/500, Loss: 0.665861947608793
Epoch 106/500, Loss: 0.6656966223948783
Epoch 106/500, Loss: 0.6656966223948783
Epoch 107/500, Loss: 0.6655356004719812
Epoch 107/500, Loss: 0.6655356004719812
Epoch 108/500, Loss: 0.6653787069331129
Epoch 108/500, Loss: 0.6653787069331129
Epoch 109/500, Loss: 0.6652257772566116
Epoch 109/500, Loss: 0.6652257772566116
Epoch 110/500, Loss: 0.6650766565468912
Epoch 110/500, Loss: 0.6650766565468912
Epoch 111/500, Loss: 0.6649311988365577
Epoch 111/500, Loss: 0.6649311988365577
Epoch 112/500, Loss: 0.664789266444668
Epoch 112/500, Loss: 0.664789266444668
Epoch 113/500, Loss: 0.6646507293863629
Epoch 113/500, Loss: 0.6646507293863629
Epoch 114/500, Loss: 0.6645154648295183
Epoch 114/500, Loss: 0.6645154648295183
Epoch 115/500, Loss: 0.6643833565944409
Epoch 115/500, Loss: 0.6643833565944409
Epoch 116/500, Loss: 0.6642542946929849
Epoch 116/500, Loss: 0.6642542946929849
Epoch 117/500, Loss: 0.6641281749037774
Epoch 117/500, Loss: 0.6641281749037774
Epoch 118/500, Loss: 0.6640048983805286
Epoch 118/500, Loss: 0.6640048983805286
Epoch 119/500, Loss: 0.6638843712906718
Epoch 119/500, Loss: 0.6638843712906718
Epoch 120/500, Loss: 0.6637665044818081
Epoch 120/500, Loss: 0.6637665044818081
Epoch 121/500, Loss: 0.6636512131736582
Epoch 121/500, Loss: 0.6636512131736582
Epoch 122/500, Loss: 0.6635384166734151
Epoch 122/500, Loss: 0.6635384166734151
Epoch 123/500, Loss: 0.6634280381125787
Epoch 123/500, Loss: 0.6634280381125787
Epoch 124/500, Loss: 0.6633200042035148
Epoch 124/500, Loss: 0.6633200042035148
Epoch 125/500, Loss: 0.6632142450141331
Epoch 125/500, Loss: 0.6632142450141331
Epoch 126/500, Loss: 0.6631106937592159
Epoch 126/500, Loss: 0.6631106937592159
Epoch 127/500, Loss: 0.6630092866070562
Epoch 127/500, Loss: 0.6630092866070562
Epoch 128/500, Loss: 0.6629099625001731
Epoch 128/500, Loss: 0.6629099625001731
Epoch 129/500, Loss: 0.662812662988984
Epoch 129/500, Loss: 0.662812662988984
Epoch 130/500, Loss: 0.662717332077402
Epoch 130/500, Loss: 0.662717332077402
Epoch 131/500, Loss: 0.6626239160794154
Epoch 131/500, Loss: 0.6626239160794154
Epoch 132/500, Loss: 0.662532363485787
Epoch 132/500, Loss: 0.662532363485787
Epoch 133/500, Loss: 0.6624426248400824
Epoch 133/500, Loss: 0.6624426248400824
Epoch 134/500, Loss: 0.662354652623299
Epoch 134/500, Loss: 0.662354652623299
Epoch 135/500, Loss: 0.6622684011464335
Epoch 135/500, Loss: 0.6622684011464335
Epoch 136/500, Loss: 0.6621838264503769
Epoch 136/500, Loss: 0.6621838264503769
Epoch 137/500, Loss: 0.6621008862125763
Epoch 137/500, Loss: 0.6621008862125763
Epoch 138/500, Loss: 0.6620195396599496
Epoch 138/500, Loss: 0.6620195396599496
Epoch 139/500, Loss: 0.6619397474875827
Epoch 139/500, Loss: 0.6619397474875827
Epoch 140/500, Loss: 0.6618614717827715
Epoch 140/500, Loss: 0.6618614717827715
Epoch 141/500, Loss: 0.6617846759540162
Epoch 141/500, Loss: 0.6617846759540162
Epoch 142/500, Loss: 0.6617093246645958
Epoch 142/500, Loss: 0.6617093246645958
Epoch 143/500, Loss: 0.6616353837703872
Epoch 143/500, Loss: 0.6616353837703872
Epoch 144/500, Loss: 0.6615628202616216
Epoch 144/500, Loss: 0.6615628202616216
Epoch 145/500, Loss: 0.6614916022082883
Epoch 145/500, Loss: 0.6614916022082883
Epoch 146/500, Loss: 0.6614216987089258
Epoch 146/500, Loss: 0.6614216987089258
Epoch 147/500, Loss: 0.6613530798425563
Epoch 147/500, Loss: 0.6613530798425563
Epoch 148/500, Loss: 0.6612857166235422
Epoch 148/500, Loss: 0.6612857166235422
Epoch 149/500, Loss: 0.6612195809591541
Epoch 149/500, Loss: 0.6612195809591541
Epoch 150/500, Loss: 0.661154645609667
Epoch 150/500, Loss: 0.661154645609667
Epoch 151/500, Loss: 0.6610908841508019
Epoch 151/500, Loss: 0.6610908841508019
Epoch 152/500, Loss: 0.6610282709383577
Epoch 152/500, Loss: 0.6610282709383577
Epoch 153/500, Loss: 0.6609667810748762
Epoch 153/500, Loss: 0.6609667810748762
Epoch 154/500, Loss: 0.6609063903782098
Epoch 154/500, Loss: 0.6609063903782098
Epoch 155/500, Loss: 0.660847075351857
Epoch 155/500, Loss: 0.660847075351857
Epoch 156/500, Loss: 0.6607888131569519
Epoch 156/500, Loss: 0.6607888131569519
Epoch 157/500, Loss: 0.6607315815857951
Epoch 157/500, Loss: 0.6607315815857951
Epoch 158/500, Loss: 0.6606753590368262
Epoch 158/500, Loss: 0.6606753590368262
Epoch 159/500, Loss: 0.6606201244909436
Epoch 159/500, Loss: 0.6606201244909436
Epoch 160/500, Loss: 0.6605658574890841
Epoch 160/500, Loss: 0.6605658574890841
Epoch 161/500, Loss: 0.6605125381109795
Epoch 161/500, Loss: 0.6605125381109795
Epoch 162/500, Loss: 0.6604601469550199
Epoch 162/500, Loss: 0.6604601469550199
Epoch 163/500, Loss: 0.6604086651191494
Epoch 163/500, Loss: 0.6604086651191494
Epoch 164/500, Loss: 0.6603580741827295
Epoch 164/500, Loss: 0.6603580741827295
Epoch 165/500, Loss: 0.6603083561893163
Epoch 165/500, Loss: 0.6603083561893163
Epoch 166/500, Loss: 0.6602594936302847
Epoch 166/500, Loss: 0.6602594936302847
Epoch 167/500, Loss: 0.6602114694292588
Epoch 167/500, Loss: 0.6602114694292588
Epoch 168/500, Loss: 0.6601642669272924
Epoch 168/500, Loss: 0.6601642669272924
Epoch 169/500, Loss: 0.6601178698687576
Epoch 169/500, Loss: 0.6601178698687576
Epoch 170/500, Loss: 0.6600722623878983
Epoch 170/500, Loss: 0.6600722623878983
Epoch 171/500, Loss: 0.6600274289960101
Epoch 171/500, Loss: 0.6600274289960101
Epoch 172/500, Loss: 0.6599833545692114
Epoch 172/500, Loss: 0.6599833545692114
Epoch 173/500, Loss: 0.6599400243367671
Epoch 173/500, Loss: 0.6599400243367671
Epoch 174/500, Loss: 0.6598974238699387
Epoch 174/500, Loss: 0.6598974238699387
Epoch 175/500, Loss: 0.6598555390713258
Epoch 175/500, Loss: 0.6598555390713258
Epoch 176/500, Loss: 0.6598143561646775
Epoch 176/500, Loss: 0.6598143561646775
Epoch 177/500, Loss: 0.659773861685139
Epoch 177/500, Loss: 0.659773861685139
Epoch 178/500, Loss: 0.6597340424699177
Epoch 178/500, Loss: 0.6597340424699177
Epoch 179/500, Loss: 0.6596948856493416
Epoch 179/500, Loss: 0.6596948856493416
Epoch 180/500, Loss: 0.6596563786382879
Epoch 180/500, Loss: 0.6596563786382879
Epoch 181/500, Loss: 0.659618509127965
Epoch 181/500, Loss: 0.659618509127965
Epoch 182/500, Loss: 0.659581265078027
Epoch 182/500, Loss: 0.659581265078027
Epoch 183/500, Loss: 0.6595446347090024
Epoch 183/500, Loss: 0.6595446347090024
Epoch 184/500, Loss: 0.6595086064950246
Epoch 184/500, Loss: 0.6595086064950246
Epoch 185/500, Loss: 0.6594731691568435
Epoch 185/500, Loss: 0.6594731691568435
Epoch 186/500, Loss: 0.6594383116551058
Epoch 186/500, Loss: 0.6594383116551058
Epoch 187/500, Loss: 0.6594040231838936
Epoch 187/500, Loss: 0.6594040231838936
Epoch 188/500, Loss: 0.6593702931645018
Epoch 188/500, Loss: 0.6593702931645018
Epoch 189/500, Loss: 0.6593371112394487
Epoch 189/500, Loss: 0.6593371112394487
Epoch 190/500, Loss: 0.6593044672667049
Epoch 190/500, Loss: 0.6593044672667049
Epoch 191/500, Loss: 0.6592723513141296
Epoch 191/500, Loss: 0.6592723513141296
Epoch 192/500, Loss: 0.6592407536541068
Epoch 192/500, Loss: 0.6592407536541068
Epoch 193/500, Loss: 0.6592096647583695
Epoch 193/500, Loss: 0.6592096647583695
Epoch 194/500, Loss: 0.6591790752930041
Epoch 194/500, Loss: 0.6591790752930041
Epoch 195/500, Loss: 0.6591489761136263
Epoch 195/500, Loss: 0.6591489761136263
Epoch 196/500, Loss: 0.6591193582607201
Epoch 196/500, Loss: 0.6591193582607201
Epoch 197/500, Loss: 0.6590902129551339
Epoch 197/500, Loss: 0.6590902129551339
Epoch 198/500, Loss: 0.6590615315937248
Epoch 198/500, Loss: 0.6590615315937248
Epoch 199/500, Loss: 0.6590333057451452
Epoch 199/500, Loss: 0.6590333057451452
Epoch 200/500, Loss: 0.6590055271457649
Epoch 200/500, Loss: 0.6590055271457649
Epoch 201/500, Loss: 0.6589781876957252
Epoch 201/500, Loss: 0.6589781876957252
Epoch 202/500, Loss: 0.6589512794551144
Epoch 202/500, Loss: 0.6589512794551144
Epoch 203/500, Loss: 0.6589247946402649
Epoch 203/500, Loss: 0.6589247946402649
Epoch 204/500, Loss: 0.6588987256201614
Epoch 204/500, Loss: 0.6588987256201614
Epoch 205/500, Loss: 0.6588730649129616
Epoch 205/500, Loss: 0.6588730649129616
Epoch 206/500, Loss: 0.6588478051826187
Epoch 206/500, Loss: 0.6588478051826187
Epoch 207/500, Loss: 0.6588229392356044
Epoch 207/500, Loss: 0.6588229392356044
Epoch 208/500, Loss: 0.6587984600177302
Epoch 208/500, Loss: 0.6587984600177302
Epoch 209/500, Loss: 0.6587743606110577
Epoch 209/500, Loss: 0.6587743606110577
Epoch 210/500, Loss: 0.6587506342309006
Epoch 210/500, Loss: 0.6587506342309006
Epoch 211/500, Loss: 0.6587272742229092
Epoch 211/500, Loss: 0.6587272742229092
Epoch 212/500, Loss: 0.6587042740602382
Epoch 212/500, Loss: 0.6587042740602382
Epoch 213/500, Loss: 0.6586816273407929
Epoch 213/500, Loss: 0.6586816273407929
Epoch 214/500, Loss: 0.6586593277845504
Epoch 214/500, Loss: 0.6586593277845504
Epoch 215/500, Loss: 0.6586373692309536
Epoch 215/500, Loss: 0.6586373692309536
Epoch 216/500, Loss: 0.6586157456363766
Epoch 216/500, Loss: 0.6586157456363766
Epoch 217/500, Loss: 0.6585944510716547
Epoch 217/500, Loss: 0.6585944510716547
Epoch 218/500, Loss: 0.6585734797196826
Epoch 218/500, Loss: 0.6585734797196826
Epoch 219/500, Loss: 0.6585528258730734
Epoch 219/500, Loss: 0.6585528258730734
Epoch 220/500, Loss: 0.6585324839318772
Epoch 220/500, Loss: 0.6585324839318772
Epoch 221/500, Loss: 0.6585124484013609
Epoch 221/500, Loss: 0.6585124484013609
Epoch 222/500, Loss: 0.6584927138898409
Epoch 222/500, Loss: 0.6584927138898409
Epoch 223/500, Loss: 0.6584732751065724
Epoch 223/500, Loss: 0.6584732751065724
Epoch 224/500, Loss: 0.6584541268596902
Epoch 224/500, Loss: 0.6584541268596902
Epoch 225/500, Loss: 0.6584352640542
Epoch 225/500, Loss: 0.6584352640542
Epoch 226/500, Loss: 0.6584166816900198
Epoch 226/500, Loss: 0.6584166816900198
Epoch 227/500, Loss: 0.6583983748600672
Epoch 227/500, Loss: 0.6583983748600672
Epoch 228/500, Loss: 0.6583803387483934
Epoch 228/500, Loss: 0.6583803387483934
Epoch 229/500, Loss: 0.6583625686283621
Epoch 229/500, Loss: 0.6583625686283621
Epoch 230/500, Loss: 0.6583450598608693
Epoch 230/500, Loss: 0.6583450598608693
Epoch 231/500, Loss: 0.6583278078926076
Epoch 231/500, Loss: 0.6583278078926076
Epoch 232/500, Loss: 0.6583108082543684
Epoch 232/500, Loss: 0.6583108082543684
Epoch 233/500, Loss: 0.6582940565593843
Epoch 233/500, Loss: 0.6582940565593843
Epoch 234/500, Loss: 0.658277548501709
Epoch 234/500, Loss: 0.658277548501709
Epoch 235/500, Loss: 0.6582612798546345
Epoch 235/500, Loss: 0.6582612798546345
Epoch 236/500, Loss: 0.6582452464691428
Epoch 236/500, Loss: 0.6582452464691428
Epoch 237/500, Loss: 0.6582294442723939
Epoch 237/500, Loss: 0.6582294442723939
Epoch 238/500, Loss: 0.6582138692662459
Epoch 238/500, Loss: 0.6582138692662459
Epoch 239/500, Loss: 0.658198517525808
Epoch 239/500, Loss: 0.658198517525808
Epoch 240/500, Loss: 0.6581833851980265
Epoch 240/500, Loss: 0.6581833851980265
Epoch 241/500, Loss: 0.6581684685002994
Epoch 241/500, Loss: 0.6581684685002994
Epoch 242/500, Loss: 0.6581537637191229
Epoch 242/500, Loss: 0.6581537637191229
Epoch 243/500, Loss: 0.6581392672087659
Epoch 243/500, Loss: 0.6581392672087659
Epoch 244/500, Loss: 0.6581249753899738
Epoch 244/500, Loss: 0.6581249753899738
Epoch 245/500, Loss: 0.658110884748699
Epoch 245/500, Loss: 0.658110884748699
Epoch 246/500, Loss: 0.658096991834858
Epoch 246/500, Loss: 0.658096991834858
Epoch 247/500, Loss: 0.6580832932611158
Epoch 247/500, Loss: 0.6580832932611158
Epoch 248/500, Loss: 0.6580697857016952
Epoch 248/500, Loss: 0.6580697857016952
Epoch 249/500, Loss: 0.6580564658912099
Epoch 249/500, Loss: 0.6580564658912099
Epoch 250/500, Loss: 0.6580433306235236
Epoch 250/500, Loss: 0.6580433306235236
Epoch 251/500, Loss: 0.6580303767506315
Epoch 251/500, Loss: 0.6580303767506315
Epoch 252/500, Loss: 0.658017601181564
Epoch 252/500, Loss: 0.658017601181564
Epoch 253/500, Loss: 0.6580050008813152
Epoch 253/500, Loss: 0.6580050008813152
Epoch 254/500, Loss: 0.6579925728697901

In [67]:
model.bias

tensor([-0.5554], dtype=torch.float64, requires_grad=True)

### Evaluation

In [68]:
# model evaluation

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()*100:.2f}%')

Accuracy: 59.65%