In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

In [8]:
X_train[:5]

array([[ 9.62894201e-01,  3.28349799e-01,  1.00468719e+00,
         8.29095483e-01,  1.12339091e+00,  1.20308638e+00,
         1.24985194e+00,  1.43836939e+00,  6.08949244e-01,
        -1.32110626e-01,  1.39442527e+00,  3.41300428e-01,
         1.28087533e+00,  1.10407102e+00,  6.54457092e-01,
         1.38740170e+00,  7.43254781e-01,  1.08512628e+00,
        -3.14125180e-01,  4.44895089e-01,  8.21589172e-01,
        -1.08826116e-01,  7.21639276e-01,  6.90064311e-01,
         4.15516406e-01,  6.08980536e-01,  4.33842719e-01,
         5.36399364e-01, -7.36200392e-01, -3.55666816e-01],
       [ 1.24001765e+00, -5.32685637e-01,  1.16895103e+00,
         1.14731264e+00,  6.76162779e-01,  1.05546169e-01,
         7.36354768e-01,  9.54349637e-01,  5.90047538e-01,
        -6.22010529e-02,  1.04951394e+00,  6.75981224e-01,
         9.67141509e-01,  1.03140998e+00,  3.45974624e-01,
        -2.51772821e-01,  7.72314742e-02,  6.89248919e-01,
         2.54165065e-02,  2.97003895e-01,  1.18625045e+00,
        -1.43659070e-01,  1.09139252e+00,  1.11650681e+00,
         7.90712476e-01, -1.67748481e-01,  2.79156506e-01,
         7.78136432e-01,  4.30471357e-03,  5.07622696e-02],
       [-1.71898186e+00, -5.99285066e-01, -1.69293547e+00,
        -1.31051469e+00, -7.46169150e-01, -8.76800954e-01,
        -9.38574910e-01, -1.12972307e+00, -1.54677913e-01,
         3.69155914e-01, -8.99147451e-01, -4.78390098e-01,
        -8.81699204e-01, -7.06223071e-01,  6.31692111e-01,
        -5.13190389e-01, -5.49487889e-01, -9.75580275e-01,
         6.98141456e-01, -4.41708922e-01, -1.53559768e+00,
        -6.31320536e-01, -1.51581132e+00, -1.13966763e+00,
        -1.18586205e-01, -7.68796444e-01, -1.00608182e+00,
        -1.37712455e+00,  3.66825789e-01, -5.41899681e-01],
       [ 1.66984165e+00,  1.09662175e+00,  2.08472180e+00,
         1.61916149e+00,  2.37709594e+00,  4.67830706e+00,
         3.69992995e+00,  2.85816050e+00,  4.14355993e+00,
         2.80706644e+00,  1.81602240e+00,  1.23809695e+00,
         2.79312110e+00,  1.57911336e+00,  1.09755015e+00,
         2.46811914e+00,  2.78134346e+00,  2.32554197e+00,
         7.46481323e+00,  8.23541105e-01,  1.41570020e+00,
         9.87582803e-01,  1.82794094e+00,  1.24426699e+00,
         1.39102614e+00,  2.32460570e+00,  2.47211933e+00,
         2.04611588e+00,  4.37861109e+00,  9.04376566e-01],
       [-6.74396217e-01, -2.40123868e-01, -6.41236365e-01,
        -6.63688481e-01, -1.86767474e-01,  2.10443825e-01,
        -2.87285060e-01, -4.71378833e-01,  5.93827903e-01,
         8.80301595e-02, -4.08918172e-01,  6.42698050e-01,
        -3.98695052e-01, -4.26245838e-01,  6.00019038e-01,
         9.49599028e-01,  1.00766325e+00,  9.92754936e-01,
         9.76641893e-01,  3.73178989e-01, -6.57542467e-01,
         2.21257657e-01, -6.59758687e-01, -6.40712559e-01,
         3.58133495e-01,  3.18109334e-01,  4.73759212e-02,
        -3.67760137e-02,  8.68513703e-01, -7.48937251e-04]], dtype=float32)

In [9]:
y_train

156    M
121    M
46     B
78     M
216    B
      ..
145    B
310    B
243    B
7      M
220    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
y_train = LabelEncoder().fit_transform(y_train).astype(np.float32)
y_test = LabelEncoder().fit_transform(y_test).astype(np.float32)

In [11]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
type(y_train_tensor)

torch.Tensor

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
X_test_tensor.shape

torch.Size([114, 30])

In [16]:
X_train_tensor.dtype

torch.float32

In [17]:
X_test_tensor.dtype

torch.float32

In [18]:
y_test_tensor.dtype

torch.float32

In [19]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [20]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [21]:
train_dataset[10]

(tensor([-0.5556, -0.6754, -0.5644, -0.5550, -0.3268, -0.7047, -0.7084, -0.6960,
         -0.3399, -0.5069, -0.5693, -0.3521, -0.5675, -0.4638, -0.7256, -0.4138,
         -0.4644, -0.6378, -0.8126, -0.5450, -0.4814, -0.4240, -0.5559, -0.5028,
         -0.6527, -0.4560, -0.5012, -0.4503, -0.4699, -0.4287]),
 tensor(0.))

In [22]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

### Defining the Model

In [23]:
import torch.nn as nn

class BreastCancerNN(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

### Important Parameeter

In [24]:
learning_rate = 0.1
epochs = 500

In [25]:
loss_function = nn.BCELoss()

In [26]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training Pipeline

In [27]:
import torch.optim as optim

In [28]:
# create model
model = BreastCancerNN(X_train_tensor.shape[1])
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

#define loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
        # forward pass
        y_pred = model(batch_features)

        # loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1, 1))

        # backward pass
        loss.backward()

        # parameter update
        optimizer.step()

        optimizer.zero_grad()

    # print loss in each epoch
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/500, Loss: 0.14295364916324615
Epoch 2/500, Loss: 0.17704012989997864
Epoch 3/500, Loss: 0.3270171582698822
Epoch 4/500, Loss: 0.06417589634656906
Epoch 5/500, Loss: 0.0316922590136528
Epoch 6/500, Loss: 0.12730802595615387
Epoch 7/500, Loss: 0.008829724974930286
Epoch 8/500, Loss: 0.07238442450761795
Epoch 9/500, Loss: 0.07802511006593704
Epoch 10/500, Loss: 0.1402594894170761
Epoch 11/500, Loss: 0.09697290509939194
Epoch 12/500, Loss: 0.1598176807165146
Epoch 13/500, Loss: 0.04167436808347702
Epoch 14/500, Loss: 0.010273496620357037
Epoch 15/500, Loss: 0.12743057310581207
Epoch 16/500, Loss: 0.013255784288048744
Epoch 17/500, Loss: 0.02678643725812435
Epoch 18/500, Loss: 0.06819013506174088
Epoch 19/500, Loss: 0.07455166429281235
Epoch 20/500, Loss: 0.07176252454519272
Epoch 21/500, Loss: 0.003990861587226391
Epoch 22/500, Loss: 0.0031018147710710764
Epoch 23/500, Loss: 0.05389998108148575
Epoch 24/500, Loss: 0.03296787291765213
Epoch 25/500, Loss: 0.010505813173949718
Epoch 26/500, Loss: 0.038699857890605927
Epoch 27/500, Loss: 0.2969001829624176
Epoch 28/500, Loss: 0.33006957173347473
Epoch 29/500, Loss: 0.6634184718132019
Epoch 30/500, Loss: 0.04100928455591202
Epoch 31/500, Loss: 0.0030515347607433796
Epoch 32/500, Loss: 0.048645131289958954
Epoch 33/500, Loss: 0.07611910998821259
Epoch 34/500, Loss: 0.02805592492222786
Epoch 35/500, Loss: 0.008019204251468182
Epoch 36/500, Loss: 0.06952732056379318
Epoch 37/500, Loss: 0.005914505571126938
Epoch 38/500, Loss: 0.7115556597709656
Epoch 39/500, Loss: 0.01847003772854805
Epoch 40/500, Loss: 0.061132196336984634
Epoch 41/500, Loss: 0.0037101819179952145
Epoch 42/500, Loss: 0.08133496344089508
Epoch 43/500, Loss: 0.32890820503234863
Epoch 44/500, Loss: 0.04464948922395706
Epoch 45/500, Loss: 0.10139273852109909
Epoch 46/500, Loss: 0.013451714999973774
Epoch 47/500, Loss: 0.04205751791596413
Epoch 48/500, Loss: 0.008821973577141762
Epoch 49/500, Loss: 0.0013203148264437914
Epoch 50/500, Loss: 0.02842012420296669
Epoch 51/500, Loss: 0.2872700095176697
Epoch 52/500, Loss: 0.0064635081216692924
Epoch 53/500, Loss: 0.05044692009687424
Epoch 54/500, Loss: 0.015416400507092476
Epoch 55/500, Loss: 0.015336217358708382
Epoch 56/500, Loss: 0.03822782635688782
Epoch 57/500, Loss: 0.002767472295090556
Epoch 58/500, Loss: 0.0021322763059288263
Epoch 59/500, Loss: 0.00521529046818614
Epoch 60/500, Loss: 0.7641614675521851
Epoch 61/500, Loss: 0.015801826491951942
Epoch 62/500, Loss: 0.7001098990440369
Epoch 63/500, Loss: 0.03787361830472946
Epoch 64/500, Loss: 0.017906665802001953
Epoch 65/500, Loss: 0.29083141684532166
Epoch 66/500, Loss: 0.01803917996585369
Epoch 67/500, Loss: 0.040550075471401215
Epoch 68/500, Loss: 0.07787342369556427
Epoch 69/500, Loss: 0.12078451365232468
Epoch 70/500, Loss: 0.007562155835330486
Epoch 71/500, Loss: 0.002435836475342512
Epoch 72/500, Loss: 0.04821363463997841
Epoch 73/500, Loss: 0.00033238469040952623
Epoch 74/500, Loss: 0.010425749234855175
Epoch 75/500, Loss: 0.7171034812927246
Epoch 76/500, Loss: 0.02160915546119213
Epoch 77/500, Loss: 0.04283557087182999
Epoch 78/500, Loss: 0.022776136174798012
Epoch 79/500, Loss: 0.03311358764767647
Epoch 80/500, Loss: 0.009887909516692162
Epoch 81/500, Loss: 0.014285862445831299
Epoch 82/500, Loss: 0.035666175186634064
Epoch 83/500, Loss: 0.020758256316184998
Epoch 84/500, Loss: 0.0736677497625351
Epoch 85/500, Loss: 0.04247622936964035
Epoch 86/500, Loss: 0.015557682141661644
Epoch 87/500, Loss: 0.015653999522328377
Epoch 88/500, Loss: 0.7529270052909851
Epoch 89/500, Loss: 0.001411433913744986
Epoch 90/500, Loss: 0.05879753828048706
Epoch 91/500, Loss: 0.001263877609744668
Epoch 92/500, Loss: 0.016439927741885185
Epoch 93/500, Loss: 0.0003109560057055205
Epoch 94/500, Loss: 0.007734029553830624
Epoch 95/500, Loss: 0.001643998664803803
Epoch 96/500, Loss: 0.0027104343753308058
Epoch 97/500, Loss: 0.021390127018094063
Epoch 98/500, Loss: 0.009146156720817089
Epoch 99/500, Loss: 0.06451574712991714
Epoch 100/500, Loss: 0.04015777260065079
Epoch 101/500, Loss: 0.018458137288689613
Epoch 102/500, Loss: 0.010458067990839481
Epoch 103/500, Loss: 0.01263651717454195
Epoch 104/500, Loss: 0.007643976714462042
Epoch 105/500, Loss: 0.01050784345716238
Epoch 106/500, Loss: 0.058315347880125046
Epoch 107/500, Loss: 0.2910296320915222
Epoch 108/500, Loss: 0.0021886273752897978
Epoch 109/500, Loss: 0.004014072939753532
Epoch 110/500, Loss: 0.08183122426271439
Epoch 111/500, Loss: 0.01137533038854599
Epoch 112/500, Loss: 0.08141601085662842
Epoch 113/500, Loss: 0.037989143282175064
Epoch 114/500, Loss: 0.02387685887515545
Epoch 115/500, Loss: 0.0022634416818618774
Epoch 116/500, Loss: 0.005391902290284634
Epoch 117/500, Loss: 0.027364123612642288
Epoch 118/500, Loss: 0.02461567334830761
Epoch 119/500, Loss: 0.011408859863877296
Epoch 120/500, Loss: 0.0003011959488503635
Epoch 121/500, Loss: 0.0132298544049263
Epoch 122/500, Loss: 0.05198454484343529
Epoch 123/500, Loss: 0.0022987641859799623
Epoch 124/500, Loss: 0.00853924173861742
Epoch 125/500, Loss: 0.09635774046182632
Epoch 126/500, Loss: 0.026742273941636086
Epoch 127/500, Loss: 0.05828956142067909
Epoch 128/500, Loss: 0.015262722969055176
Epoch 129/500, Loss: 0.01350825373083353
Epoch 130/500, Loss: 0.025968223810195923
Epoch 131/500, Loss: 0.010977708734571934
Epoch 132/500, Loss: 0.013156476430594921
Epoch 133/500, Loss: 0.0863199308514595
Epoch 134/500, Loss: 0.02381712757050991
Epoch 135/500, Loss: 0.009687154553830624
Epoch 136/500, Loss: 0.0026415439788252115
Epoch 137/500, Loss: 0.117794930934906
Epoch 138/500, Loss: 0.01725347712635994
Epoch 139/500, Loss: 0.10207760334014893
Epoch 140/500, Loss: 0.02717403881251812
Epoch 141/500, Loss: 0.04583777114748955
Epoch 142/500, Loss: 0.13751360774040222
Epoch 143/500, Loss: 0.034059491008520126
Epoch 144/500, Loss: 0.0066672745160758495
Epoch 145/500, Loss: 0.04948117583990097
Epoch 146/500, Loss: 0.12431804835796356
Epoch 147/500, Loss: 0.0012726560235023499
Epoch 148/500, Loss: 0.003351179650053382
Epoch 149/500, Loss: 0.008953171782195568
Epoch 150/500, Loss: 0.007537390571087599
Epoch 151/500, Loss: 0.07754380255937576
Epoch 152/500, Loss: 0.02504936419427395
Epoch 153/500, Loss: 0.0026594342198222876
Epoch 154/500, Loss: 0.0012506021885201335
Epoch 155/500, Loss: 0.038130443543195724
Epoch 156/500, Loss: 0.013592866249382496
Epoch 157/500, Loss: 0.36205464601516724
Epoch 158/500, Loss: 0.07435496151447296
Epoch 159/500, Loss: 0.015012609772384167
Epoch 160/500, Loss: 0.4456363618373871
Epoch 161/500, Loss: 0.10203398019075394
Epoch 162/500, Loss: 0.09175217151641846
Epoch 163/500, Loss: 0.0039341687224805355
Epoch 164/500, Loss: 0.0030654636211693287
Epoch 165/500, Loss: 0.0022370931692421436
Epoch 166/500, Loss: 0.09934290498495102
Epoch 167/500, Loss: 0.02073095366358757
Epoch 168/500, Loss: 0.014182887971401215
Epoch 169/500, Loss: 0.06229399889707565
Epoch 170/500, Loss: 0.015990769490599632
Epoch 171/500, Loss: 0.04064661264419556
Epoch 172/500, Loss: 0.3119240403175354
Epoch 173/500, Loss: 0.005233552306890488
Epoch 174/500, Loss: 0.006064017303287983
Epoch 175/500, Loss: 0.004053320270031691
Epoch 176/500, Loss: 0.030618591234087944
Epoch 177/500, Loss: 0.018352335318922997
Epoch 178/500, Loss: 0.007158615626394749
Epoch 179/500, Loss: 0.03498048707842827
Epoch 180/500, Loss: 0.004027403425425291
Epoch 181/500, Loss: 0.10706507414579391
Epoch 182/500, Loss: 0.004555669147521257
Epoch 183/500, Loss: 0.00026706242351792753
Epoch 184/500, Loss: 0.011872104369103909
Epoch 185/500, Loss: 0.0781610980629921
Epoch 186/500, Loss: 0.14105607569217682
Epoch 187/500, Loss: 0.0017860156949609518
Epoch 188/500, Loss: 0.05910251662135124
Epoch 189/500, Loss: 0.005767255090177059
Epoch 190/500, Loss: 0.18580849468708038
Epoch 191/500, Loss: 0.025722777470946312
Epoch 192/500, Loss: 0.0018888808554038405
Epoch 193/500, Loss: 0.0162216704338789
Epoch 194/500, Loss: 0.34440547227859497
Epoch 195/500, Loss: 0.009133103303611279
Epoch 196/500, Loss: 0.13319149613380432
Epoch 197/500, Loss: 0.1401570439338684
Epoch 198/500, Loss: 0.05469807982444763
Epoch 199/500, Loss: 0.00406276248395443
Epoch 200/500, Loss: 0.03595763072371483
Epoch 201/500, Loss: 0.0032495686318725348
Epoch 202/500, Loss: 0.004263277165591717
Epoch 203/500, Loss: 0.00720293028280139
Epoch 204/500, Loss: 0.014898441731929779
Epoch 205/500, Loss: 0.0003912602551281452
Epoch 206/500, Loss: 0.0027207848615944386
Epoch 207/500, Loss: 0.04094830900430679
Epoch 208/500, Loss: 0.018798062577843666
Epoch 209/500, Loss: 0.0018094213446602225
Epoch 210/500, Loss: 0.005620964802801609
Epoch 211/500, Loss: 0.0005874693160876632
Epoch 212/500, Loss: 0.016671432182192802
Epoch 213/500, Loss: 0.019319279119372368
Epoch 214/500, Loss: 0.002654046518728137
Epoch 215/500, Loss: 0.13651485741138458
Epoch 216/500, Loss: 0.08509000390768051
Epoch 217/500, Loss: 0.08282724767923355
Epoch 218/500, Loss: 0.01846429891884327
Epoch 219/500, Loss: 0.05732244625687599
Epoch 220/500, Loss: 0.017133820801973343
Epoch 221/500, Loss: 0.03988704830408096
Epoch 222/500, Loss: 0.02866499498486519
Epoch 223/500, Loss: 0.0029191174544394016
Epoch 224/500, Loss: 0.14939944446086884
Epoch 225/500, Loss: 0.009009922854602337
Epoch 226/500, Loss: 0.0050328755751252174
Epoch 227/500, Loss: 0.04294074699282646
Epoch 228/500, Loss: 5.975184103590436e-05
Epoch 229/500, Loss: 0.0017158176051452756
Epoch 230/500, Loss: 0.042752329260110855
Epoch 231/500, Loss: 0.0018451862270012498
Epoch 232/500, Loss: 0.017029142007231712
Epoch 233/500, Loss: 0.06501904875040054
Epoch 234/500, Loss: 0.00401492090895772
Epoch 235/500, Loss: 0.06213963031768799
Epoch 236/500, Loss: 0.06511930376291275
Epoch 237/500, Loss: 0.008389240130782127
Epoch 238/500, Loss: 0.013167038559913635
Epoch 239/500, Loss: 0.24198193848133087
Epoch 240/500, Loss: 0.009652110747992992
Epoch 241/500, Loss: 0.0022042137570679188
Epoch 242/500, Loss: 0.021983368322253227
Epoch 243/500, Loss: 0.006207497324794531
Epoch 244/500, Loss: 0.050894223153591156
Epoch 245/500, Loss: 0.02705538645386696
Epoch 246/500, Loss: 0.013140031136572361
Epoch 247/500, Loss: 0.07507648319005966
Epoch 248/500, Loss: 0.014370625838637352
Epoch 249/500, Loss: 0.00958963017910719
Epoch 250/500, Loss: 0.21255923807621002
Epoch 251/500, Loss: 0.011151263490319252
Epoch 252/500, Loss: 0.17780733108520508
Epoch 253/500, Loss: 0.0007888866239227355
Epoch 254/500, Loss: 0.01283801905810833
Epoch 255/500, Loss: 0.002419321332126856
Epoch 256/500, Loss: 0.0195171982049942
Epoch 257/500, Loss: 0.03723998740315437
Epoch 258/500, Loss: 0.8205142617225647
Epoch 259/500, Loss: 0.031517188996076584
Epoch 260/500, Loss: 0.039804380387067795
Epoch 261/500, Loss: 0.012041611596941948
Epoch 262/500, Loss: 0.0008272353443317115
Epoch 263/500, Loss: 0.025098813697695732
Epoch 264/500, Loss: 0.004544849041849375
Epoch 265/500, Loss: 0.07079792767763138
Epoch 266/500, Loss: 0.00195976416580379
Epoch 267/500, Loss: 0.0006635027821175754
Epoch 268/500, Loss: 0.050490230321884155
Epoch 269/500, Loss: 0.2584860622882843
Epoch 270/500, Loss: 0.3679528832435608
Epoch 271/500, Loss: 0.0036437646485865116
Epoch 272/500, Loss: 0.006432395428419113
Epoch 273/500, Loss: 0.041249096393585205
Epoch 274/500, Loss: 0.05579470843076706
Epoch 275/500, Loss: 0.033383987843990326
Epoch 276/500, Loss: 0.0015518369618803263
Epoch 277/500, Loss: 0.009646034799516201
Epoch 278/500, Loss: 0.08024760335683823
Epoch 279/500, Loss: 0.0107598677277565
Epoch 280/500, Loss: 0.09089231491088867
Epoch 281/500, Loss: 0.015857171267271042
Epoch 282/500, Loss: 0.08554083108901978
Epoch 283/500, Loss: 0.018047450110316277
Epoch 284/500, Loss: 0.014922223053872585
Epoch 285/500, Loss: 0.0009507009526714683
Epoch 286/500, Loss: 0.10387425124645233
Epoch 287/500, Loss: 0.002675133291631937
Epoch 288/500, Loss: 0.0004437812604010105
Epoch 289/500, Loss: 0.0006357181700877845
Epoch 290/500, Loss: 0.020626017823815346
Epoch 291/500, Loss: 0.06986887753009796
Epoch 292/500, Loss: 0.01120105292648077
Epoch 293/500, Loss: 0.007153164129704237
Epoch 294/500, Loss: 0.018643897026777267
Epoch 295/500, Loss: 0.8108204007148743
Epoch 296/500, Loss: 0.011301063932478428
Epoch 297/500, Loss: 0.0076011172495782375
Epoch 298/500, Loss: 0.01725592091679573
Epoch 299/500, Loss: 0.004620720166712999
Epoch 300/500, Loss: 0.009609261527657509
Epoch 301/500, Loss: 0.001019040122628212
Epoch 302/500, Loss: 0.008594736456871033
Epoch 303/500, Loss: 0.004821263253688812
Epoch 304/500, Loss: 0.07576912641525269
Epoch 305/500, Loss: 0.0019716774113476276
Epoch 306/500, Loss: 0.0021108146756887436
Epoch 307/500, Loss: 0.0002502238203305751
Epoch 308/500, Loss: 0.002443239325657487
Epoch 309/500, Loss: 0.02352631464600563
Epoch 310/500, Loss: 0.0544738732278347
Epoch 311/500, Loss: 0.03960379958152771
Epoch 312/500, Loss: 0.040176015347242355
Epoch 313/500, Loss: 0.0009552898118272424
Epoch 314/500, Loss: 0.012872780673205853
Epoch 315/500, Loss: 0.005544401705265045
Epoch 316/500, Loss: 0.007561566773802042
Epoch 317/500, Loss: 0.011155917309224606
Epoch 318/500, Loss: 0.08457241207361221
Epoch 319/500, Loss: 0.00011916875519091263
Epoch 320/500, Loss: 0.001971297664567828
Epoch 321/500, Loss: 0.003171690972521901
Epoch 322/500, Loss: 0.0653979480266571
Epoch 323/500, Loss: 0.0568477101624012
Epoch 324/500, Loss: 0.036966122686862946
Epoch 325/500, Loss: 0.02313506416976452
Epoch 326/500, Loss: 0.0005518249818123877
Epoch 327/500, Loss: 0.12915995717048645
Epoch 328/500, Loss: 0.03398921713232994
Epoch 329/500, Loss: 0.0044281273148953915
Epoch 330/500, Loss: 0.0007458124891854823
Epoch 331/500, Loss: 0.006773711647838354
Epoch 332/500, Loss: 0.0952783152461052
Epoch 333/500, Loss: 0.04247773438692093
Epoch 334/500, Loss: 0.009825118817389011
Epoch 335/500, Loss: 0.00450810045003891
Epoch 336/500, Loss: 0.014214306138455868
Epoch 337/500, Loss: 0.01676672138273716
Epoch 338/500, Loss: 0.004022355657070875
Epoch 339/500, Loss: 0.02688021957874298
Epoch 340/500, Loss: 0.007320739328861237
Epoch 341/500, Loss: 0.013995363377034664
Epoch 342/500, Loss: 0.7580264210700989
Epoch 343/500, Loss: 0.003166325856000185
Epoch 344/500, Loss: 0.09955598413944244
Epoch 345/500, Loss: 0.0006337918457575142
Epoch 346/500, Loss: 0.023187143728137016
Epoch 347/500, Loss: 0.00036534437094815075
Epoch 348/500, Loss: 0.04083101823925972
Epoch 349/500, Loss: 0.004424888640642166
Epoch 350/500, Loss: 0.08515992015600204
Epoch 351/500, Loss: 0.020256873220205307
Epoch 352/500, Loss: 0.002722864504903555
Epoch 353/500, Loss: 0.07319523394107819
Epoch 354/500, Loss: 0.001711975783109665
Epoch 355/500, Loss: 0.012939738109707832
Epoch 356/500, Loss: 0.000517134671099484
Epoch 357/500, Loss: 0.062114864587783813
Epoch 358/500, Loss: 0.010471480898559093
Epoch 359/500, Loss: 0.1483202427625656
Epoch 360/500, Loss: 0.05369511619210243
Epoch 361/500, Loss: 0.007587127853184938
Epoch 362/500, Loss: 0.0036126638296991587
Epoch 363/500, Loss: 0.7502058744430542
Epoch 364/500, Loss: 0.07141716778278351
Epoch 365/500, Loss: 0.0014980287523940206
Epoch 366/500, Loss: 0.00019541583606041968
Epoch 367/500, Loss: 0.005857604555785656
Epoch 368/500, Loss: 0.0012491035740822554
Epoch 369/500, Loss: 0.0016207058215513825
Epoch 370/500, Loss: 0.17569176852703094
Epoch 371/500, Loss: 0.06692270934581757
Epoch 372/500, Loss: 0.1251203864812851
Epoch 373/500, Loss: 0.006765902973711491
Epoch 374/500, Loss: 0.019079800695180893
Epoch 375/500, Loss: 0.0031542370561510324
Epoch 376/500, Loss: 0.0013049922417849302
Epoch 377/500, Loss: 0.0021779669914394617
Epoch 378/500, Loss: 0.026441972702741623
Epoch 379/500, Loss: 0.00034016071003861725
Epoch 380/500, Loss: 0.0004502722586039454
Epoch 381/500, Loss: 0.004459110088646412
Epoch 382/500, Loss: 0.003757755970582366
Epoch 383/500, Loss: 0.012216771952807903
Epoch 384/500, Loss: 0.0019288150360807776
Epoch 385/500, Loss: 0.01060890406370163
Epoch 386/500, Loss: 0.007031577173620462
Epoch 387/500, Loss: 0.010249239392578602
Epoch 388/500, Loss: 0.011765806004405022
Epoch 389/500, Loss: 0.0021199900656938553
Epoch 390/500, Loss: 0.021221192553639412
Epoch 391/500, Loss: 0.2159813940525055
Epoch 392/500, Loss: 0.0028616173658519983
Epoch 393/500, Loss: 0.019081654027104378
Epoch 394/500, Loss: 0.022181913256645203
Epoch 395/500, Loss: 0.0041669984348118305
Epoch 396/500, Loss: 0.022374821826815605
Epoch 397/500, Loss: 0.01103209052234888
Epoch 398/500, Loss: 0.02460021898150444
Epoch 399/500, Loss: 0.06476988643407822
Epoch 400/500, Loss: 0.012768407352268696
Epoch 401/500, Loss: 0.030509818345308304
Epoch 402/500, Loss: 0.0483044795691967
Epoch 403/500, Loss: 0.018900806084275246
Epoch 404/500, Loss: 0.008736914023756981
Epoch 405/500, Loss: 0.20779740810394287
Epoch 406/500, Loss: 0.010705402120947838
Epoch 407/500, Loss: 0.001202131388708949
Epoch 408/500, Loss: 0.07863813638687134
Epoch 409/500, Loss: 0.01835392415523529
Epoch 410/500, Loss: 0.07485713064670563
Epoch 411/500, Loss: 0.06386864930391312
Epoch 412/500, Loss: 0.09632770717144012
Epoch 413/500, Loss: 0.05884307250380516
Epoch 414/500, Loss: 0.763120710849762
Epoch 415/500, Loss: 0.012471443973481655
Epoch 416/500, Loss: 0.11495590209960938
Epoch 417/500, Loss: 0.035385776311159134
Epoch 418/500, Loss: 0.02482377365231514
Epoch 419/500, Loss: 0.01767045632004738
Epoch 420/500, Loss: 6.395815580617636e-05
Epoch 421/500, Loss: 0.06968912482261658
Epoch 422/500, Loss: 0.004936080425977707
Epoch 423/500, Loss: 0.008870535530149937
Epoch 424/500, Loss: 0.0021249677520245314
Epoch 425/500, Loss: 0.006599568761885166
Epoch 426/500, Loss: 0.002547253156080842
Epoch 427/500, Loss: 0.002733187284320593
Epoch 428/500, Loss: 0.0006209643324837089
Epoch 429/500, Loss: 0.0018151423428207636
Epoch 430/500, Loss: 0.003285920713096857
Epoch 431/500, Loss: 0.014249579980969429
Epoch 432/500, Loss: 0.0033307967241853476
Epoch 433/500, Loss: 0.0043882941827178
Epoch 434/500, Loss: 0.12591001391410828
Epoch 435/500, Loss: 0.008008328266441822
Epoch 436/500, Loss: 0.005511655006557703
Epoch 437/500, Loss: 0.05471894145011902
Epoch 438/500, Loss: 0.014547801576554775
Epoch 439/500, Loss: 0.019512346014380455
Epoch 440/500, Loss: 0.024319516494870186
Epoch 441/500, Loss: 0.20803245902061462
Epoch 442/500, Loss: 0.04379837587475777
Epoch 443/500, Loss: 0.07183963060379028
Epoch 444/500, Loss: 0.00415276363492012
Epoch 445/500, Loss: 0.005399796646088362
Epoch 446/500, Loss: 0.018102630972862244
Epoch 447/500, Loss: 0.047648970037698746
Epoch 448/500, Loss: 0.006089262198656797
Epoch 449/500, Loss: 5.5409411288565025e-05
Epoch 450/500, Loss: 0.0007791189709678292
Epoch 451/500, Loss: 0.003234625095501542
Epoch 452/500, Loss: 0.01661807671189308
Epoch 453/500, Loss: 0.0017950332257896662
Epoch 454/500, Loss: 0.004203894641250372
Epoch 455/500, Loss: 0.006222628057003021
Epoch 456/500, Loss: 2.9485188406397356e-06
Epoch 457/500, Loss: 0.00038054908509366214
Epoch 458/500, Loss: 0.005287424195557833
Epoch 459/500, Loss: 0.12664420902729034
Epoch 460/500, Loss: 0.05778205394744873
Epoch 461/500, Loss: 0.04737408831715584
Epoch 462/500, Loss: 0.029843533411622047
Epoch 463/500, Loss: 0.003050637198612094
Epoch 464/500, Loss: 0.04560968279838562
Epoch 465/500, Loss: 0.003964992240071297
Epoch 466/500, Loss: 0.06173408031463623
Epoch 467/500, Loss: 0.03613705560564995
Epoch 468/500, Loss: 0.20066602528095245
Epoch 469/500, Loss: 0.0002838273358065635
Epoch 470/500, Loss: 0.1307922750711441
Epoch 471/500, Loss: 0.00023055185738485307
Epoch 472/500, Loss: 0.003513564122840762
Epoch 473/500, Loss: 0.046215590089559555
Epoch 474/500, Loss: 0.003931241109967232
Epoch 475/500, Loss: 0.010206558741629124
Epoch 476/500, Loss: 0.0468892939388752
Epoch 477/500, Loss: 0.3241153061389923
Epoch 478/500, Loss: 0.010390026494860649
Epoch 479/500, Loss: 0.026887672021985054
Epoch 480/500, Loss: 0.001259883982129395
Epoch 481/500, Loss: 0.11404456198215485
Epoch 482/500, Loss: 0.0022967688273638487

In [29]:
model.linear.weight

Parameter containing:
tensor([[ 0.1510,  0.4066,  0.1205,  0.4109, -0.0805, -1.1943,  1.2293,  1.4868,
         -0.2703, -0.3016,  2.0965, -0.4095,  1.1223,  1.4789,  0.3158, -0.8636,
          0.1544,  0.1923, -0.4354, -0.9899,  1.4656,  1.6755,  0.9384,  1.4607,
          1.0713, -0.1520,  1.2078,  1.1903,  0.8747,  0.7423]],
       requires_grad=True)

### Evaluation

In [31]:
# model evaluation
model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred >= 0.5).float()
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy*100:.2f}%')

Accuracy: 96.44%